### ISSUE TITLE
Link to see code on Github goes back to Glitch

### ISSUE THREAD

**Issue by mrbombmusic** [magenta/drumbot#3]
Hello,

Just noticed that when using the app on Glitch, clicking the link to see the code on Github just goes back to the Glitch app. 

It looks like the link was just left out of the html:
![Screenshot 2019-12-02 19 55 57](https://user-images.githubusercontent.com/26189509/70007391-29b36600-153e-11ea-9f16-687744ed3240.png)

Love the app!

**Comment by notwaldorf** [comment]
Ah, great catch, thanks!

**Comment by notwaldorf** [comment]
Fixed in 0036492
